export const data = {
  title: "Тестовые торги на аппарат ЛОТОС №2033564 (09.11.2020 07:00)",
  participants: [
    {
      id: 1,
      name: `ООО "СПЕЦПОСТАВКА"`,
      isOnline: false,
      qualityStandards: "нет",
      productionTime: "80",
      warranty: "24",
      termsPayment: "30",
      cost: "3700000",
      discount: "25000",
      startCost: "2475000",
      currency: "руб.",
      actions: [],
    },
    {
      id: 2,
      name: `ЛОТОС ПРО`,
      isOnline: true,
      qualityStandards: "нет",
      productionTime: "90",
      warranty: "24",
      termsPayment: "100",
      cost: "3200000",
      discount: "25000",
      startCost: "2475000",
      currency: "руб.",
      actions: [],
    },
    {
      id: 3,
      name: `ООО "УЗРО"`,
      isOnline: false,
      qualityStandards: "нет",
      productionTime: "75",
      warranty: "22",
      termsPayment: "60",
      cost: "2800000",
      discount: "25000",
      startCost: "2475000",
      currency: "руб.",
      actions: [],
    },
    {
      id: 4,
      name: `ООО "ПО РЭТО"`,
      isOnline: true,
      qualityStandards: "нет",
      productionTime: "120",
      warranty: "36",
      termsPayment: "50",
      cost: "2500000",
      discount: "25000",
      startCost: "2475000",
      currency: "руб.",
      actions: [],
    },
  ],
  startTrade: `${new Date().setUTCHours(0, 0, 0, 0)}`,
};
